[build]
  command = "NODE_OPTIONS=\"--max-old-space-size=4096\" npx prisma generate && NODE_OPTIONS=\"--max-old-space-size=4096\" next build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.18.0"

[[plugins]]
  package = "@netlify/plugin-nextjs" 